//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectDesign.Brock.Resources.zh {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObjectDesign.Brock.Resources.zh.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Copy {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制多一个 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_CopyNewOne {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.CopyNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制多十个 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_CopyNewTen {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.CopyNewTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Delete {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Move {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Move_Bottom {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Move.Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Move_Down {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Move.Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Move_Top {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Move.Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_Move_Up {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.Move.Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放进容器 的本地化字符串。
        /// </summary>
        internal static string Cdev_Actions_Menus_PutInContainer {
            get {
                return ResourceManager.GetString("Cdev.Actions.Menus.PutInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Border {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线性渐变 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Brush_Linear {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Brush.Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无笔刷 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Brush_None {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Brush.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 径向渐变 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Brush_Radial {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Brush.Radial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯色 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Brush_Solid {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Brush.Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 裁剪到边界 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_ClipToBounds {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.ClipToBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆角 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Corner {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对文件夹 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_FolderName {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Font {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_FontSize {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Height {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片名字 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_ImageName {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不确定 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_IsIndeterminate {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.IsIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Layout {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Name {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Opacity {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源路径 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_ResourcePath {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.ResourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Rotate {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Select {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉伸 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Strech {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Strech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 笔迹宽度 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_StrokeThickness {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.StrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Text {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本裁剪 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_TextTrimming {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.TextTrimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包裹 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_TextWraping_None {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.TextWraping.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包裹 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_TextWraping_Wrap {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.TextWraping.Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 溢出包裹 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_TextWraping_WrapWithOverflow {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.TextWraping.WrapWithOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本包装 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_TextWrapping {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.TextWrapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变量选择 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_VariableSelect {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.VariableSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Wdith {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Wdith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_X {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Descripts_Y {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Descripts.Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Image_Empty {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Image.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入路径 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Image_InputUri {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Image.InputUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Image_Path {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Image.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片选择 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Image_Select {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Image.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Image_SelectFile {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Image.SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程地址 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_Image_Uri {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.Image.Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_MediaElement_Pick {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.MediaElement.Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体源 的本地化字符串。
        /// </summary>
        internal static string Cdev_DesignControl_MediaElement_Source {
            get {
                return ResourceManager.GetString("Cdev.DesignControl.MediaElement.Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_Error {
            get {
                return ResourceManager.GetString("Cdev.Dialog.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常触发 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_Exception {
            get {
                return ResourceManager.GetString("Cdev.Dialog.Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入图片地址 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_InputImageUri {
            get {
                return ResourceManager.GetString("Cdev.Dialog.InputImageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片类型 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_PickImage_Filter_Image {
            get {
                return ResourceManager.GetString("Cdev.Dialog.PickImage.Filter.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_PickImage_Filter_Media {
            get {
                return ResourceManager.GetString("Cdev.Dialog.PickImage.Filter.Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一张图片 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_PickImage_Title_Image {
            get {
                return ResourceManager.GetString("Cdev.Dialog.PickImage.Title.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体选择 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_PickImage_Title_Media {
            get {
                return ResourceManager.GetString("Cdev.Dialog.PickImage.Title.Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存到文件{0} 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_SavedToFile {
            get {
                return ResourceManager.GetString("Cdev.Dialog.SavedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Cdev_Dialog_Succeed {
            get {
                return ResourceManager.GetString("Cdev.Dialog.Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所拖入的文件不符合，应为hello后缀的文件 的本地化字符串。
        /// </summary>
        internal static string Cdev_Import_FileNotSupport {
            get {
                return ResourceManager.GetString("Cdev.Import.FileNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        internal static string Cdev_Menu_Load {
            get {
                return ResourceManager.GetString("Cdev.Menu.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Cdev_Menu_Save {
            get {
                return ResourceManager.GetString("Cdev.Menu.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计模式 的本地化字符串。
        /// </summary>
        internal static string Cdev_Notify_ModeTypes_Designing {
            get {
                return ResourceManager.GetString("Cdev.Notify.ModeTypes.Designing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行模式 的本地化字符串。
        /// </summary>
        internal static string Cdev_Notify_ModeTypes_Running {
            get {
                return ResourceManager.GetString("Cdev.Notify.ModeTypes.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换模式 的本地化字符串。
        /// </summary>
        internal static string Cdev_Notify_ModeTypes_Title_SwitchMode {
            get {
                return ResourceManager.GetString("Cdev.Notify.ModeTypes.Title.SwitchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索属性 的本地化字符串。
        /// </summary>
        internal static string Cdev_PropertyPanel_Search_Descript {
            get {
                return ResourceManager.GetString("Cdev.PropertyPanel.Search.Descript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Actions_Copy {
            get {
                return ResourceManager.GetString("Cdev.Scene.Actions.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Actions_Delete {
            get {
                return ResourceManager.GetString("Cdev.Scene.Actions.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建场景 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Actions_New {
            get {
                return ResourceManager.GetString("Cdev.Scene.Actions.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入场景名字 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Create_Input_Descript {
            get {
                return ResourceManager.GetString("Cdev.Scene.Create.Input.Descript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在相同名字{0}的场景 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Create_Input_Error_SameName {
            get {
                return ResourceManager.GetString("Cdev.Scene.Create.Input.Error.SameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建场景失败 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Create_Input_Error_Title {
            get {
                return ResourceManager.GetString("Cdev.Scene.Create.Input.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建场景 的本地化字符串。
        /// </summary>
        internal static string Cdev_Scene_Create_Input_Title {
            get {
                return ResourceManager.GetString("Cdev.Scene.Create.Input.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖动创建第一个控件 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tips_DragNewControl {
            get {
                return ResourceManager.GetString("Cdev.Tips.DragNewControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画布 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_Canvas {
            get {
                return ResourceManager.GetString("Cdev.Tools.Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_Image {
            get {
                return ResourceManager.GetString("Cdev.Tools.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直线 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_Line {
            get {
                return ResourceManager.GetString("Cdev.Tools.Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_Media {
            get {
                return ResourceManager.GetString("Cdev.Tools.Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度条 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_ProgressBar {
            get {
                return ResourceManager.GetString("Cdev.Tools.ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_Rectangle {
            get {
                return ResourceManager.GetString("Cdev.Tools.Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本块 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_TextBlock {
            get {
                return ResourceManager.GetString("Cdev.Tools.TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_TextBox {
            get {
                return ResourceManager.GetString("Cdev.Tools.TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        internal static string Cdev_Tools_ToolBox {
            get {
                return ResourceManager.GetString("Cdev.Tools.ToolBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的字符串不是有效Uri 的本地化字符串。
        /// </summary>
        internal static string Cdev_Uri_InputNotUri {
            get {
                return ResourceManager.GetString("Cdev.Uri.InputNotUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主窗口 的本地化字符串。
        /// </summary>
        internal static string Cdev_Window_Main {
            get {
                return ResourceManager.GetString("Cdev.Window.Main", resourceCulture);
            }
        }
    }
}
